# Generated by Django 4.1.3 on 2022-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobt', models.CharField(max_length=150)),
                ('describe', models.CharField(max_length=400)),
                ('skills', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('cont', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Job',
                'ordering': ['id'],
            },
        ),
    ]
